### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by appcoders** [phatblat/OpenSSL#1]
The Linker misses lots of stuff. Where did I go wrong?

Undefined symbols for architecture x86_64:
  "_ASN1_OCTET_STRING_it", referenced from:
      _SSL_SESSION_ASN1_seq_tt in ssl_asn1.o
  "_ASN1_get_object", referenced from:
      _ssl3_get_client_key_exchange in s3_srvr.o
  "_ASN1_item_d2i", referenced from:
      _d2i_SSL_SESSION_ASN1 in ssl_asn1.o
  "_ASN1_item_free", referenced from:
      _d2i_SSL_SESSION in ssl_asn1.o
  "_ASN1_item_i2d", referenced from:
      _i2d_SSL_SESSION_ASN1 in ssl_asn1.o
  "_BIO_callback_ctrl", referenced from:
      _ssl_callback_ctrl in bio_ssl.o
  "_BIO_clear_flags", referenced from:
      _ssl_write in bio_ssl.o
      _ssl_read in bio_ssl.o
      _ssl_ctrl in bio_ssl.o
  "_BIO_copy_next_retry", referenced from:
      _ssl_ctrl in bio_ssl.o
  "_BIO_ctrl", referenced from:
      _SSL_use_certificate_file in ssl_rsa.o
      _SSL_use_RSAPrivateKey_file in ssl_rsa.o
      _SSL_use_PrivateKey_file in ssl_rsa.o
      _SSL_CTX_use_certificate_file in ssl_rsa.o
      _SSL_CTX_use_RSAPrivateKey_file in ssl_rsa.o
      _SSL_CTX_use_PrivateKey_file in ssl_rsa.o
      _use_certificate_chain_file in ssl_rsa.o
      ...

**Comment by phatblat** [comment]
My apologies. You did nothing wrong. The build for this project is not yet working. OpenSSL is a huge library with a complex build and I have not yet sorted out all the correct source files which need to be included in and excluded from Apple platform targets.

I've added a big warning to the readme to inform others of the current state of this project.

**Comment by phatblat** [comment]
FYI, I added an [Alternatives](https://github.com/phatblat/OpenSSL#alternatives) section to the readme with a list of all the comparable projects I could find.
